server:
  port: 8801
eureka:
  instance:
    hostname: localhost
  client:
  #registerWithEureka 和 fetchRegistry 设置为false，表明自己属于服务中心主体
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
